# Generated by Django 4.1.2 on 2023-06-14 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0002_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table',
            new_name='Rack',
        ),
    ]
