# Generated by Django 4.1.2 on 2023-06-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0003_rename_table_rack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('rack_no', models.IntegerField()),
                ('server_make', models.CharField(max_length=100)),
                ('server_model', models.CharField(max_length=100)),
                ('server_serial_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ownership', models.CharField(max_length=100)),
                ('warranty_amc_status', models.CharField(max_length=100)),
                ('vms', models.BooleanField()),
                ('num_of_vms', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField()),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('applications_running', models.TextField()),
                ('specification', models.TextField()),
            ],
        ),
    ]
