# Generated by Django 4.1.2 on 2023-06-14 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0004_server'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Server',
        ),
    ]
