# Generated by Django 4.1.2 on 2023-06-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0006_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='specification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
