# Generated by Django 4.1.2 on 2023-06-14 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0007_remove_company_id_alter_company_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrapp.company'),
        ),
    ]
