# Generated by Django 4.1.2 on 2023-06-14 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0008_alter_server_server_make'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='Company',
            new_name='company',
        ),
    ]
