# Generated by Django 4.1.2 on 2023-06-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0007_alter_server_specification'),
        ('qrapp', '0009_rename_company_company_company'),
    ]

    operations = [
    ]
