# Generated by Django 4.1.2 on 2023-06-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0010_merge_20230615_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='company',
            field=models.CharField(max_length=100),
        ),
    ]
