# Generated by Django 4.1.2 on 2023-06-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0011_company_id_alter_company_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='id',
        ),
        migrations.AlterField(
            model_name='company',
            name='company',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
