# Generated by Django 4.1.2 on 2023-06-15 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rack', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_no', models.IntegerField()),
                ('server_model', models.CharField(max_length=100)),
                ('server_serial_no', models.CharField(max_length=100)),
                ('ownership', models.CharField(max_length=100)),
                ('warranty_amc_status', models.CharField(max_length=100)),
                ('vms', models.BooleanField()),
                ('num_of_vms', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField()),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('applications_running', models.TextField()),
                ('specification', models.TextField(blank=True, null=True)),
                ('server_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrapp.company')),
            ],
        ),
    ]
