# Generated by Django 4.1.2 on 2023-07-12 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OwnershipChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rack', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_model', models.CharField(max_length=100, unique=True)),
                ('server_serial_no', models.CharField(max_length=100, unique=True)),
                ('warranty_amc_status', models.CharField(max_length=100)),
                ('vms', models.BooleanField(default=False)),
                ('num_of_vms', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True, unique=True)),
                ('applications_installed', models.TextField()),
                ('portals_running', models.TextField(blank=True, null=True)),
                ('specification', models.TextField(blank=True, null=True)),
                ('ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapp.ownershipchoice')),
                ('rack_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapp.rack')),
                ('server_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapp.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='racks',
            field=models.ManyToManyField(related_name='companies', to='serverapp.rack'),
        ),
    ]
