# Generated by Django 4.1.2 on 2023-07-12 10:25

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_make',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='rack_no', chained_model_field='racks', on_delete=django.db.models.deletion.CASCADE, to='serverapp.company'),
        ),
    ]
