# Generated by Django 4.1.2 on 2023-07-17 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0002_alter_server_server_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapp.company'),
        ),
    ]
