# Generated by Django 4.1.2 on 2023-07-25 05:29

from django.db import migrations, models
import serverapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0004_server_vm_information_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='vm_information_file',
            field=models.FileField(blank=True, null=True, upload_to='server_vms/', validators=[serverapp.models.validate_excel_file_extension]),
        ),
    ]
